CREATE TABLE MOVIES
(ID NUMBER,
CONSTRAINT MOVIE_PK PRIMARY KEY (ID),
TITLE NVARCHAR2(50) NOT NULL,
DIRECTOR NVARCHAR2(50) NOT NULL,
YEAR NUMBER NOT NULL,
CONSTRAINT YEAR_CHECK CHECK(YEAR BETWEEN 1900 AND 2018),
LENGHT_MINS NUMBER NOT NULL,
CONSTRAINT LENGHT_MINS_CHECK CHECK(LENGHT_MINS BETWEEN 10 AND 200));