 SELECT  DIRECTOR, COUNT(TITLE) FROM MOVIES
 GROUP BY (DIRECTOR);

SELECT MOVIE.DIRECTOR, SUM(MOVIE_STAT.DOMESTIC_SALES), SUM(MOVIE_STAT.INTERNATIONAL_SALES)
FROM MOVIE, MOVIE_STAT
WHERE MOVIE.ID = MOVIE_STAT.MOVIE_ID
GROUP BY MOVIE.DIRECTOR;