CREATE TABLE SUPPLIERS (
ID NUMBER,
CONSTRAINT SUPPLIER_PK PRIMARY KEY (ID),
CONTACT_NAME NVARCHAR2(50),
CONTACT_TITLE NVARCHAR2(50),
ADDRESS NVARCHAR2(1000),
CITY NVARCHAR2(100),
REGION NVARCHAR2(100),
POSTAL_CODE NUMBER,
COUNTRY NVARCHAR2(100),
PHONE NUMBER,
FAX NUMBER,
HOME_PAGE NVARCHAR2(1000)
);

CREATE TABLE CUSTOMERS (
ID NUMBER,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID),
CONTACT_NAME NVARCHAR2(50),
CONTACT_TITLE NVARCHAR2(50),
ADDRESS NVARCHAR2(1000),
CITY NVARCHAR2(100),
REGION NVARCHAR2(100),
POSTAL_CODE NUMBER,
COUNTRY NVARCHAR2(100),
PHONE NUMBER,
FAX NUMBER,
HOME_PAGE NVARCHAR2(1000)
);

CREATE TABLE EMPLOYEES (
ID NUMBER,
CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID),
LAST_NAME NVARCHAR2(50),
FIRST_NAME NVARCHAR2(50),
TITLE NVARCHAR2(50),
TITLE_OF_COURTESY NVARCHAR2(50),
BIRTH_DATE DATE,
HIRE_DATE DATE,
ADDRESS NVARCHAR2(1000),
CITY NVARCHAR2(100),
REGION NVARCHAR2(100),
POSTAL_CODE NUMBER,
COUNTRY NVARCHAR2(100),
HOME_PHONE NUMBER,
EXTENSION NVARCHAR2(500),
PHOTO NVARCHAR2(50),
NOTES NVARCHAR2(1000),
REPORTS_TO NVARCHAR2(1000)
);

CREATE TABLE CATEGORIES (
ID NUMBER,
CONSTRAINT CATEGORY_PK PRIMARY KEY (ID),
DESCRIPTION NVARCHAR2(1000),
PICTURE NVARCHAR2(50)
);

CREATE TABLE SHIPPERS (
ID NUMBER,
CONSTRAINT SHIPPER_PK PRIMARY KEY (ID),
COMPANY_NAME NVARCHAR2(50),
PHONE NUMBER
);

CREATE TABLE PRODUCTS (
ID NUMBER,
CONSTRAINT PRODUCT_PK PRIMARY KEY (ID),
PRODUCT_NAME NVARCHAR2(100),
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID),
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
QUANTITY_PER_UNIT NUMBER,
UNITS_IN_STOCK NUMBER,
UNITS_ON_ORDER NUMBER,
REORDER_LEVEL NVARCHAR2(50),
DISCONTINUED NVARCHAR2(50)
);

CREATE TABLE ORDERS (
ID NUMBER,
CONSTRAINT ORDER_PK PRIMARY KEY (ID),
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
EMPLOYEE_ID NUMBER,
CONSTRAINT EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
ORDER_DATE DATE,
REQUIRED_DATE DATE,
SHIPPED_DATE DATE,
SHIP_VIA NVARCHAR2(50),
FREIGHT NVARCHAR2(50),
SHIP_NAME NVARCHAR2(50),
SHIP_ADDRESS NVARCHAR2(50),
SHIP_CITY NVARCHAR2(50),
SHIP_REGION NVARCHAR2(50),
SHIP_POSTAL_CODE NUMBER,
SHIP_COUNTRY NVARCHAR2
);

CREATE TABLE ORDER_DETAILS (
ID NUMBER,
ORDER_ID NUMBER,
CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
UNIT_PRICE NUMBER,
QUANTITY NUMBER,
DISCOUNT NUMBER
);

