CREATE TABLE FORUM_CATEGORIES (
ID NUMBER,
CONSTRAINT FORUM_CATEGORY_PK PRIMARY KEY (ID),
TITLE NVARCHAR2(64),
DESCRIPTION CLOB,
DATE_CREATE DATE,
IP VARCHAR(20)
);

CREATE TABLE FORUM_SUBCATEGORIES (
ID NUMBER,
CONSTRAINT FORUM_SUBCATEGORY_PK PRIMARY KEY (ID),
FORUM_CATEGORY_ID NUMBER,
CONSTRAINT FORUM_CATEGORY_ID_FK FOREIGN KEY (FORUM_CATEGORY_ID) REFERENCES FORUM_CATEGORIES(ID),
TITLE VARCHAR(45),
DESCRIPTION CLOB,
DATE_CREATE TIMESTAMP,
IP VARCHAR(20)
);

CREATE TABLE USERS (
ID NUMBER,
CONSTRAINT USER_PK PRIMARY KEY(ID),
NICK NVARCHAR2(16),
PASSWORD VARCHAR(128),
EMAIL NVARCHAR2(128),
DATE_CREATE TIMESTAMP,
KARMA NUMBER(9,2),
IP NVARCHAR2(20)
);

CREATE TABLE FORUM_POSTS (
ID NUMBER,
CONSTRAINT FORUM_POST_PK PRIMARY KEY(ID),
ID_SUBCATEGORY NUMBER,
CONSTRAINT ID_SUBCATEGORY_FK FOREIGN KEY (ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES(ID),
ID_USER NUMBER,
CONSTRAINT ID_USER_FK FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
PARENT_POST NUMBER,
CONSTRAINT PARENT_POST_FK FOREIGN KEY (PARENT_POST) REFERENCES FORUM_POSTS(ID),
TITLE NVARCHAR2(90),
CONTENT BLOB,
IS_POLL CHAR(1) DEFAULT 'N',
DATE_POST TIMESTAMP,
IP NVARCHAR2(20)
);

CREATE TABLE FORUM_POLLS_OPTIONS (
ID NUMBER,
CONSTRAINT FORUM_POLLS_OPTIONS_PK PRIMARY KEY(ID),
ID_POST NUMBER,
CONSTRAINT ID_POST_FK FOREIGN KEY(ID_POST) REFERENCES FORUM_POSTS(ID),
TITLE NVARCHAR2(64),
DATE_CREATE TIMESTAMP
);

CREATE TABLE FORUM_POLLS_OPTIONS_VOTES (
ID NUMBER,
CONSTRAINT FORUM_POLL_OPTION_VOTE_PK PRIMARY KEY(ID),
ID_POLL_OPTION NUMBER,
CONSTRAINT POLL_OPTION_FK FOREIGN KEY(ID_POLL_OPTION) REFERENCES FORUM_POLLS_OPTIONS(ID),
ID_USER NUMBER,
CONSTRAINT USER_FK FOREIGN KEY(ID_USER) REFERENCES USERS(ID),
DATE_CREATE TIMESTAMP,
IP NVARCHAR2(20)
);
