SELECT
CUSTOMER.NAME, SALESMAN.NAME, SALESMAN.CITY, CUSTOMER.CITY, DEALS.AMOUNT
FROM CUSTOMER
JOIN SALESMAN ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEALS ON DEALS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEALS.AMOUNT > 10000;

SELECT CUSTOMER.NAME, DEALS.DATE_DEAL FROM CUSTOMER
JOIN DEALS ON CUSTOMER.CUSTOMER_ID = DEALS.CUSTOMER_ID
WHERE DEALS.DATE_DEAL BETWEEN TO_DATE('01.01.2017', 'DD.MM.YYYY') AND TO_DATE('31.12.2018', 'DD.MM.YYYY');


SELECT SALESMAN.NAME, SUM(DEALS.AMOUNT)
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEALS ON DEALS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEALS.DATE_DEAL BETWEEN TO_DATE('01.01.2017', 'DD.MM.YYYY') AND TO_DATE('31.12.2018', 'DD.MM.YYYY')
GROUP BY SALESMAN.NAME ;


SELECT SALERMAN_NAME FROM
(SELECT SALESMAN.NAME AS SALERMAN_NAME, SUM (DEALS.AMOUNT) AS SUMA,
FIRST_VALUE (SUM(DEALS.AMOUNT)) OVER (ORDER BY SUM(DEALS.AMOUNT) DESC) AS MAX_SUMA
FROM SALESMAN
INNER JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
INNER JOIN DEALS ON DEALS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEALS.DATE_DEAL BETWEEN TO_DATE('01.08.2017', 'DD.MM.YYYY') AND TO_DATE('31.08.2017', 'DD.MM.YYYY')
GROUP BY SALESMAN.NAME)
WHERE SUMA = MAX_SUMA;
