--ALTER TABLE table name
--ADD COLUMN NAME TYPE....

--ALTER TABLE table name
--DROP COLUMN COLUMN name....

--ALTER TABLE TABLE name
--MODIFY COLUMN NAME TYPE....

ALTER TABLE CUSTOMER
ADD AGE NUMBER;

ALTER TABLE CUSTOMER
DROP COLUMN AGE;

ALTER TABLE CUSTOMER
MODIFY NAME NVARCHAR2(90);

ALTER TABLE CUSTOMER
ADD AGE NUMBER DEFAULT 0 NOT NULL;